//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::wb_followee::Entity as WbFollowee;
pub use super::wb_follower::Entity as WbFollower;
pub use super::wb_super_follower::Entity as WbSuperFollower;